name: Build Docker image

inputs:
  version:
    required: true
    type: string
  latest:
    required: false
    type: boolean
    default: false
  github-token:
    required: true
    type: string
  docker-image-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Log in to registry
      run: echo "${{ inputs.github-token }}" | docker login ghcr.io -u $ --password-stdin
      shell: bash
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL3045,DL3007
    - name: Build and push image
      run: |
        IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/${{ inputs.docker-image-name }}" | tr '[A-Z]' '[a-z]')
        echo "IMAGE_ID=$IMAGE_ID" >> "$GITHUB_OUTPUT"
        echo $IMAGE_ID
        docker build --tag $IMAGE_ID:${{ inputs.version }} --platform=linux/amd64 --no-cache .
        docker push $IMAGE_ID:${{ inputs.version }}
      shell: bash
    - name: Tag latest
      if: inputs.latest
      run: |
        IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/${{ inputs.docker-image-name }}" | tr '[A-Z]' '[a-z]')
        echo $IMAGE_ID
        docker tag $IMAGE_ID:${{ inputs.version }} $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
      shell: bash
